// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBinV7_Tdr5CLDpd8qY4YCgHaVQmuhdL2w',
    appId: '1:419097967193:web:b5d1d5c554269a3a714f48',
    messagingSenderId: '419097967193',
    projectId: 'basurawatch-davao-2026',
    authDomain: 'basurawatch-davao-2026.firebaseapp.com',
    storageBucket: 'basurawatch-davao-2026.firebasestorage.app',
    measurementId: 'G-TXZT6S716D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj7Ax-5XNTt8vjeHNJYBkqpcU6GSHkMbg',
    appId: '1:419097967193:android:7c811ccbb2e44c81714f48',
    messagingSenderId: '419097967193',
    projectId: 'basurawatch-davao-2026',
    storageBucket: 'basurawatch-davao-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBMiCXTDBeseHmdgcaH116GomsoDclam4',
    appId: '1:419097967193:ios:b6bb24e36fb8ad95714f48',
    messagingSenderId: '419097967193',
    projectId: 'basurawatch-davao-2026',
    storageBucket: 'basurawatch-davao-2026.firebasestorage.app',
    iosClientId: '419097967193-a264nsrbpir31j6mfb6am059pgaf2s75.apps.googleusercontent.com',
    iosBundleId: 'com.example.basuraWatchFinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBMiCXTDBeseHmdgcaH116GomsoDclam4',
    appId: '1:419097967193:ios:b6bb24e36fb8ad95714f48',
    messagingSenderId: '419097967193',
    projectId: 'basurawatch-davao-2026',
    storageBucket: 'basurawatch-davao-2026.firebasestorage.app',
    iosClientId: '419097967193-a264nsrbpir31j6mfb6am059pgaf2s75.apps.googleusercontent.com',
    iosBundleId: 'com.example.basuraWatchFinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBinV7_Tdr5CLDpd8qY4YCgHaVQmuhdL2w',
    appId: '1:419097967193:web:e06d6ff3312490eb714f48',
    messagingSenderId: '419097967193',
    projectId: 'basurawatch-davao-2026',
    authDomain: 'basurawatch-davao-2026.firebaseapp.com',
    storageBucket: 'basurawatch-davao-2026.firebasestorage.app',
    measurementId: 'G-PE7H011LRJ',
  );
}
